permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

auto: false

highlighter: rouge

# 作者信息
author: 
  name: WangSir
  email: wyuelin@gmail.com
  link: http://wyuelin.github.com
  weibo: http://weibo.com/u/1751001864
  github: http://github.com/wyuelin

# 站点信息
title: WangSir的博客 
description: WangSir的博客
url: http://wyuelin.github.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/wangsir.jpg
favicon: /public/img/wangsir.ico

# google analytics 设置
ga:
  id: UA-54685312-1
  url: wyuelin.github.com

# disqus 设置
disqus:
  shortname: wangsir

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - C++

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
